version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: socks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Wertyrwer
